### ISSUE TITLE
fix(config): EV battery-discharge permission silently does nothing while its power ceiling is 0

### ISSUE THREAD

**Issue by woopstar** [woopstar/hsem#991]
## Description

Letting the Huawei battery cover house load while an EV charges requires **two** settings, but only one of them looks like a switch — and enabling that switch alone silently does nothing.

```python
# custom_components/hsem/const.py:53-54 (and :84-85 for the second EV)
"hsem_ev_charger_force_max_discharge_power": False,
"hsem_ev_charger_max_discharge_power": 0,
```

The permission boolean defaults off, and the power ceiling it governs defaults to **0**. Both the planner and the applier fail closed on a zero ceiling, independently:

- `planner/milp/_ev_amp_lattice.py:35-49` — `ev_discharge_cap_kwh()` returns `0.0` when
  `force_max_discharge_power` is False **or** `max_discharge_power_w <= 0`. The MILP then binds
  `ed + (max_dis - cap)*on <= max_dis`, so it plans zero battery discharge for every slot where
  that EV is commanded on.
- `custom_sensors/applier_caps.py::_planned_ev_discharge_cap_w()` — computes
  `min(planned_power_w, max_discharge_power_w, *ev_ceilings)`. With an EV ceiling of `0`, the
  result is `0` → a 0 W cap is written to *Maximum discharging power*.

So a user who enables **EV Charger Force Max Discharge Power** and leaves **EV Charger Max
Discharge Power** at its `0` default gets exactly the behaviour they were trying to turn off,
with no error, no warning, and no log line saying why. `flows/ev_helpers.py:179` already validates
this step — it checks both fields are *present* (`standard_required`), but never checks that they
are *coherent with each other*.

The current UI text does not hint at the dependency either:

| Field | Current `data_description` (`translations/en.json`) |
| --- | --- |
| `..._force_max_discharge_power` | "Enable this if you want to force a specific maximum discharge power for the Huawei batteries while EV is charging." |
| `..._max_discharge_power` | "Set the maximum discharge power for the Huawei batteries while EV is charging." |

Neither says that leaving the switch **off** means the battery will not discharge *at all* while an
EV is charging.

### Why this matters now

This is the permission model introduced by #797 in v6.3.0, which replaced v6.2.4's automatic
house-only-load discharge cap (`compute_ev_discharge_cap_w`, #592). In v6.2.4 the battery covered
base house load whenever an EV charged — planned or unplanned/"ghost" — with no setting required.
From v6.3.0 it does not, unless both settings above are configured.

Two secondary gaps around the same change:

1. **#797 is not mentioned anywhere in the v6.3.0 / v6.3.1 release notes**, so this is a silent
   behaviour regression for every EV user upgrading from 6.2.x.
2. **The setting name is misleading.** "Force max discharge power" reads as *force the battery to
   discharge at maximum power*. It actually means *permit any battery discharge while an EV is
   charging*, with the companion field supplying the ceiling.

Real-world evidence: this trap is live in
[#978](https://github.com/woopstar/hsem/issues/978#issuecomment-5651916959), where @Extati asked
whether v6.3.1 preserves the v6.2.4 behaviour. The first answer given was "enable *Force max
discharge power*" — which on a default config would have changed nothing.

**Not in scope:** flipping `force_max_discharge_power` to default `True`. Fail-closed is correct
here — Huawei exposes one *global* battery discharge limit and `MaximizeSelfConsumption` follows
total AC load, so it cannot distinguish house load from EV load. That is exactly why v6.2.4 had to
*estimate* house-only load by subtracting EV power from the net sensor. Permission-on means the
home battery may physically feed the car (round-trip losses plus cycle wear), which should stay an
explicit opt-in. The planner and applier already agree on the current semantics, so this is a
usability defect, not a plan-vs-hardware contradiction like #983.

## Possible Solution

**Primary — reject the incoherent combination at the config flow.** In
`flows/ev_helpers.py::validate_ev_charger_input()`, add a cross-field check after the existing
`standard_required` pass: when `f"{prefix}_charger_force_max_discharge_power"` is truthy and
`f"{prefix}_charger_max_discharge_power"` is missing, non-numeric or `<= 0`, return an error keyed
to the power field. Add the error key to all four `translations/{en,da,de,es}.json` files (activate
the `hsem-translation-sync` skill). This covers both EV steps, since `ev.py` and `ev_second.py`
both delegate here.

Keep the `0` default for the ceiling — there is no safe universal wattage, since it depends on
battery rating, charger rating and the phase/fuse layout. Making `0` *invalid when the permission
is on* is the fix, not guessing a value.

**Secondary — surface configs already saved in the bad state.** Config-flow validation only runs on
submit, so an existing entry keeps the silent 0 W. Emit one clear warning (not per-cycle debug
spam) when the applier caps to 0 W for an EV whose permission is on but whose ceiling is `<= 0`,
naming both settings. `applier.py:248` already builds the `blocked` tuple and a `cap_reason` string
— this is a distinct sub-case worth its own reason text.

An alternative considered and **not** recommended: treating permission-on-with-ceiling-0 as "use
the battery's rated maximum". It self-heals existing configs, but silently picks a discharge-into-EV
ceiling the user never chose — the wrong trade-off for a safety-shaped opt-in.

**Tertiary — clarify the wording.** Update the two `data_description` strings (all four locales) to
state the dependency explicitly and say what happens when the switch is off, e.g. "While this is
off, the Huawei battery will not discharge at all while this EV is charging — house load is served
from the grid. Enable it and set a maximum discharge power below to let the battery cover house
load." Renaming the config key itself is **out of scope** (it would need a config migration); only
the user-visible label and description change.

## Acceptance Criteria

- [ ] Submitting the EV step with `force_max_discharge_power` enabled and `max_discharge_power` of
      `0` returns a validation error on the power field instead of saving
- [ ] The same validation applies to the second EV step (`hsem_ev_second` prefix)
- [ ] `force_max_discharge_power` disabled with a `0` ceiling remains valid (the default config
      must still pass validation)
- [ ] `force_max_discharge_power` enabled with a positive ceiling remains valid
- [ ] Non-numeric or negative ceilings with the permission enabled are rejected
- [ ] An existing config entry already in the incoherent state produces one clear warning naming
      both settings when the applier caps to 0 W, and does not spam every cycle
- [ ] The `0` default for `hsem_ev_charger_max_discharge_power` is unchanged, and
      `hsem_ev_charger_force_max_discharge_power` still defaults to `False`
- [ ] `data_description` for both fields, in all four locales, states what happens when the
      permission is off
- [ ] `./scripts/quality.sh translations` reports 0 missing/stale/placeholder-mismatch keys
- [ ] Tests added/updated covering the above
- [ ] `./scripts/quality.sh all` passes

## Suggested Prompt

```
In HSEM, letting the Huawei battery cover house load while an EV charges requires two settings, and
enabling only the obvious one silently does nothing.

`hsem_ev_charger_force_max_discharge_power` defaults to False and `hsem_ev_charger_max_discharge_power`
defaults to 0 (custom_components/hsem/const.py:53-54, and :84-85 for the second EV). Both the planner
(`planner/milp/_ev_amp_lattice.py::ev_discharge_cap_kwh`, returns 0.0 when the ceiling is <= 0) and the
applier (`custom_sensors/applier_caps.py::_planned_ev_discharge_cap_w`, computes min(..., 0) = 0) fail
closed on a zero ceiling. So enabling the permission while leaving the ceiling at its 0 default still
produces a 0 W cap, with no error or warning.

Fix, in order:

1. Add a cross-field check to `flows/ev_helpers.py::validate_ev_charger_input()` — when
   `{prefix}_charger_force_max_discharge_power` is truthy and `{prefix}_charger_max_discharge_power` is
   missing, non-numeric or <= 0, return an error keyed to the power field. This covers both EV steps,
   which delegate here from `flows/ev.py` and `flows/ev_second.py`. Add the new error key to all four
   `translations/{en,da,de,es}.json`.
2. Emit one clear warning (not per-cycle debug spam) when the applier caps to 0 W for an EV whose
   permission is on but whose ceiling is <= 0 — config-flow validation cannot reach entries already
   saved in that state. `applier.py` around line 248 already builds the `blocked` tuple and `cap_reason`.
3. Update the `data_description` for both fields in all four locales to state that while the permission
   is off, the battery will not discharge at all while that EV is charging.

Do NOT change either default: `0` has no safe universal value (it depends on battery rating, charger
rating and phase/fuse layout), and permission-on must stay an explicit opt-in because Huawei exposes a
single global discharge limit that cannot distinguish house load from EV load. Do NOT rename the config
key (it would need a migration) — label and description only.

Activate the `hsem-pre-flight`, `hsem-canonical-helpers`, `hsem-ha-compliance`, `hsem-translation-sync`
and `hsem-code-quality` skills. Add tests alongside the existing EV flow tests. Run
`./scripts/quality.sh all` and `./scripts/quality.sh translations` before opening the PR.

Note this repo currently ships fixes twice: one PR based on `v6.3.0-hotfix` and a cherry-pick PR based
on `main` (which is heading to 7.0.0). Confirm with the maintainer whether this one is hotfix-worthy or
main-only before branching.
```
