### ISSUE TITLE
fix(milp): a charge-past-target EV blocks all house-battery charging beyond PV surplus

### ISSUE THREAD

**Issue by woopstar** [woopstar/hsem#1015]
## Description

Two defects that both let a charge-past-target EV break the spec guarantee in
`docs/planner-spec.md` — *"past-target charging never draws from the battery or grid"* —
in ways #1012/#1013 does not address. Defect A is the more expensive of the two and is
**pre-existing**, not introduced by #1013.

### Defect A — a past-target EV blocks all house-battery charging beyond PV surplus

The battery-first row (issue #775) in `planner/milp/_ev_constraints.py:267-272` is:

```
ec[t] + Σ_ev ev_c[t] / η_charger  ≤  surplus[t]
```

Its *intent* is an ordering rule: the house battery takes its share of the slot's PV
surplus before a past-target EV absorbs any. But `ec` is the **total** battery-charge
variable — `planner/milp/_layout.py:132` declares a single `battery_charge` block with no
PV-sourced / grid-sourced split (`grid_import` at `:134` is a separate site-level
variable). So the row does not merely order the two consumers; it caps *all* battery
charging at the PV surplus.

At night `surplus[t] == 0`, so the row forces `ec[t] == 0` and the house battery cannot
charge at all — including from cheap grid.

Reproduced against `main` (16 × 15-min slots, 8 cheap night slots at 0.20 followed by 8
expensive slots at 3.00 with a 1.2 kWh/slot house load, battery 2.0/14.25 kWh, zero PV):

```
battery grid-charge over the 8 cheap night slots
  without past-target EV : 7.897 kWh
  with    past-target EV : 0.000 kWh
```

**Exposure window:** `hsem_ev_allow_charge_past_target_soc` enabled, car plugged in, and
`target_soc ≤ SoC < 100 %`. At 100 % the EV is excluded from the MILP entirely
(`planner/engine_ev_milp.py:259`, `elif not allow_past_target or soc_pct >= 100: continue`),
so `charge_past_target` is never set and the row is not emitted — which is why a field log
showing `primary EV excluded` at 100 % SoC does *not* show this. The window is exactly the
common case of a car arriving home part-charged above its target and sitting plugged in
overnight.

**Not caused by #1013.** Verified byte-identical behaviour with and without that PR's
pro-rating: at night the full-slot and pro-rated budgets are both zero.

### Defect B — the command deadband can hold a past-target command above the surplus

`coordinator_ev_command_stability.py` runs **after** the MILP and can raise the published
command above what the surplus-only constraint allowed. At `:424-431`:

```python
if planned_a >= previous_a:
    return planned_w
if previous_a - planned_a >= spec.deadband_a:
    return planned_w
if self._holding_cost_exceeds_bypass(...):
    return planned_w
return previous_w          # ← holds the higher, stale ceiling
```

Only *downward* moves are damped, and a drop smaller than `deadband_a`
(`hsem_ev_planned_load_command_deadband_a`, default **3 A** ≈ 2.1 kW on three phases,
≈ 690 W on one) holds the previous higher ceiling. The stability layer has **no
past-target awareness** — `_EvCommandSpec` carries no such field — and its only safety
clamps are the charger rating and the site fuse budget, neither of which is a surplus cap.

The cost bypass cannot release it either. It prices a hold as *time-shifting* energy
between slots:

```python
extra_cost = (held_kwh - planned_kwh) * (price_now - price_alt)
return extra_cost > EV_COMMAND_DEADBAND_COST_BYPASS_FRACTION * planned_cost   # 0.05
```

A past-target EV has no deadline, so nothing is being shifted — the held excess is simply
new grid import. On a stable-price sunny afternoon `price_now ≈ price_alt`, so
`extra_cost ≈ 0` and the bypass never fires.

The justifying comment states *"a charger that follows PV surplus itself only has to react
when the ceiling drops below what it is already drawing."* That assumption does not hold
for an OCPP-controlled charger: the profile is a hard current limit and the vehicle draws
up to it, with HSEM as the only thing doing PV-following.

**Severity note:** unlike #1012, this leak is *not* hidden. `write_ev_slot_commands`
(`coordinator_helpers.py:160-171`) carries the held-vs-planned delta into
`grid_import_kwh` and re-derives `estimated_cost_currency`, so the resulting import is
visible in the published plan. The MILP objective never priced it (the stability layer
runs after the solve), but the accounting is honest. This is a genuine violation of the
surplus-only guarantee, but a smaller and self-reporting one — it should not gate Defect A.

## Possible Solution

> **Implemented in #1016 (`main`) and #1017 (`v6.3.0-hotfix`).** The column approach originally proposed below is **unsound** and was not used — see "Why the column approach fails".

### Defect A

**Two-stage solve** (`planner/milp/_past_target_reservation.py`), used by `candidate_generator.py`:

1. **Stage 1** solves with every charge-past-target EV removed and reserves, per LP slot, the AC energy spent on the house battery (`batteries_charged_kwh / η`) and on the other EVs.
2. **Stage 2** attaches that reservation (`EVConfig.past_target_reserved_ac_kwh`) and caps the past-target EVs at the PV stage 1 left unused:

```
Σ ev_c[t] / η_charger  ≤  max(0, S_full[t] − reserved[t]) × remaining_fraction[t]
```

The battery then needs no row and is free to grid-charge. The EV gains nothing from the battery yielding surplus, so it cannot displace it. The second solve runs only while a past-target EV is active, and a stage-1 failure fails closed. The #775 objective cap is skipped in reservation mode: it priced the EV below export even when the battery stored nothing, starving the EV entirely on a plain sunny day.

**Why the column approach fails.** An `ec_from_surplus[t] ≤ ec[t]` column is a free label: nothing forces the solver to make it large, so it sets it to 0 and hands the whole surplus to the EV while the battery "charges from grid". A per-slot binary disjunction (battery shares the budget *or* the EV gets nothing) fixes the night case but still leaks across slots. Fuzzing found the EV taking surplus the battery would have stored, with the battery refilling from cheap grid later — **+1.04 kWh** of grid import on a random day, even though every per-slot bound held. Only the counterfactual closes that path: with a strict price spread the two-stage solve raises grid import by at most **+0.001 kWh** (rounding) across 120 random days.

### Defect B

Give the stability layer past-target awareness and clamp accordingly: add a
`past_target: bool` field to `_EvCommandSpec`, derived in `_resolve_ev_command_specs` from
`cfg`'s `allow_charge_past_target_soc` plus the SoC/target already on the spec
(`capacity_kwh`, `target_soc_pct`, `ev_live.effective_soc_pct`). In `_decide_command_w`,
never hold a past-target EV's command *above* the planned command — the anti-flap hold
remains correct for deadline-driven EVs, where holding genuinely time-shifts energy.

No MILP changes are required for this half. Implemented as `_EvCommandSpec.allow_charge_past_target` plus `_ev_is_past_target()`, with a past-target command following the plan in both directions.

## Acceptance Criteria

- [ ] With a charge-past-target EV connected and `target_soc ≤ SoC < 100 %`, the house
      battery can still charge from grid in cheap slots — the night scenario above charges
      comparably with and without the EV present.
- [ ] A past-target EV still cannot charge from grid or battery in any slot: the
      surplus-only and battery-first guarantees from #1012/#1013 continue to hold, live
      slot included (the existing `test_ev_past_target_surplus_prorating.py` suite must
      stay green).
- [ ] Battery-first ordering (issue #775) is preserved: when the battery has headroom it
      takes the slot's PV surplus ahead of the past-target EV.
- [ ] The published command for a past-target EV never exceeds the surplus-derived planned
      command, at any point in the slot, regardless of the deadband.
- [ ] The anti-flap deadband still damps downward churn for deadline-driven (below-target)
      EVs — the past-target clamp must not disable stability generally.
- [ ] Energy balance, SoC bounds, `winner.cost == final_output.cost`, terminal-SoC
      accounting and the safety gates in `docs/planner-spec.md` all still hold.
- [ ] `docs/planner-spec.md` updated to state that the battery-first row constrains only
      surplus-sourced battery charging, and that past-target commands are not subject to
      an upward hold.
- [ ] Tests added/updated covering the above
- [ ] `./scripts/quality.sh all` passes

## Suggested Prompt

```
Fix two ways a charge-past-target EV breaks the surplus-only guarantee, neither addressed
by #1012/#1013.

Start with the hsem-pre-flight skill (checkout main, pull, read AGENTS.md and
docs/planner-spec.md), then branch as feat/1015-past-target-surplus-budget.

NOTE: already implemented in #1016 / #1017 — the ec_from_surplus column below was rejected as unsound; see Possible Solution. This is
planner work: follow the hsem-planner-change skill and keep the spec invariants satisfied.

DEFECT A — a past-target EV blocks all house-battery charging beyond PV surplus.
The battery-first row at planner/milp/_ev_constraints.py:267-272 is
    ec[t] + Σ ev_c[t]/η ≤ surplus[t]
but `ec` is the TOTAL battery-charge variable (planner/milp/_layout.py:132 declares one
`battery_charge` block, no PV/grid split), so the row caps all battery charging at the PV
surplus instead of merely ordering battery before EV. At night surplus is 0, so ec is
forced to 0 and the battery cannot grid-charge at all. Measured on main: 7.897 kWh of
cheap-night charging without the EV, 0.000 kWh with it. Window: allow_charge_past_target_soc
on and target_soc ≤ SoC < 100% (at 100% engine_ev_milp.py:259 excludes the EV entirely).
This is pre-existing — identical before and after #1013.

Fix: add an `ec_from_surplus[t]` column with ec_from_surplus[t] ≤ ec[t] and put only that
term in the battery-first row. Thread it through _layout.py, _bounds.py, _constraints.py
(energy balance), _ev_constraints.py and _write_results.py. Do NOT instead add grid import
to the row's RHS — the EV shares that budget and it would re-open #1012.

DEFECT B — the command deadband can hold a past-target command above the surplus.
coordinator_ev_command_stability.py:424-431 damps only downward moves; a drop smaller than
deadband_a (default 3 A) holds the previous higher ceiling. The layer has no past-target
awareness and its only clamps are charger rating and fuse budget. The cost bypass cannot
release it: it prices a hold as time-shifting energy, (held-planned)*(price_now-price_alt),
and a past-target EV has no deadline, so on flat prices that is ~0.

Fix: add `past_target: bool` to _EvCommandSpec, derive it in _resolve_ev_command_specs from
cfg.allow_charge_past_target_soc plus the SoC/target already on the spec, and in
_decide_command_w never hold a past-target EV's command above the planned command. Keep the
existing hold behaviour for deadline-driven EVs.

Tests: battery still grid-charges at night with a past-target EV connected; the EV still
cannot draw from grid/battery in any slot (tests/planner/test_ev_past_target_surplus_prorating.py
must stay green); battery-first ordering preserved; a past-target command is never held
above plan; the deadband still damps churn for below-target EVs.

Finish with ./scripts/quality.sh lint, typing, quality, test, then open a PR with the
hsem-pr-workflow skill. Per the repo's release workflow this needs two PRs — one based on
`v6.3.0-hotfix` and one on `main`.
```

**Comment by woopstar** [comment]
**Field validation — 2026-09-14 logs**

The reported 94 → 100 % charge was two events:

1. **11:00–13:03 (94 → 99.9 %)** — essentially excess PV. 96 % of the 5,097 Wh the charger metered fits inside the measured PV surplus. The house battery was full and never fed the EV. The remainder came during cloud dips, where the slot-entry power hold kept the command high. That exemption is now in #1016 / #1017.
2. **16:25–16:27 (to 100 %)** — grid, at ~10.9 kW. A one-cycle `connected=False` blip released the enforced 0 A profile. This is a separate defect, filed as #1018.
